language: node_js

node_js:
- 10.10.0

branches:
  only:
  - develop
  - QA
  - staging
  - master

before_script:
- npm install -g firebase-tools
- npm install cypress

script:
- npm run build
- npm run build:functions
- npm run cypress-run

after_success:
- npm run firebase:deploy