language: node_js

node_js:
- 10.10.0

branches:
  only:
  - develop
  - qa
  - staging
  - master

before_script:
- npm install -g firebase-tools

script:
- npm run build
- npm run build:functions

after_success:
- npm run firebase:deploy